---
- hosts: 172.31.30.14
  become: yes
  tasks: 
    - name: i want to copy file master to node
      copy:
        src: mytestfile
        dest: /home/maha/myfolder

    - name: i want to download file from internet
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.6/bin/apache-tomcat-10.1.6.exe
        dest: /home/maha/myfolder/apache-tomcat-10.1.6.exe
        force_basic_auth: yes

    - name: i want to install apache2 server
      apt:
        name: apache2
        state: present

    - name: i want to copy index file to node side(change the template)
      template:
         src: myindex.j2
         dest: /var/www/html/index.html