---
- hosts: 172.31.30.14
  become: yes
  tasks:
    - name: i want to execute the command
      command: hostname -f
      register: myresult

    - name: i want to display the result
      debug:
        msg: "{{myresult}}"

    - name: i want to install git
      apt:
        name: git
        state: present
      when: myresult.stderr !==""

    - name: i want to install tree
      apt:
        name: tree
        state: present
      when: myresult.stderr ==""