---
- hosts: all
  become: yes
  tasks:
    - name: install apache2 webserver
      apt:
        name: apache2
        state: present
      when: ansible_os_family=="Debian"

    - name: want to start apache webserver on ubuntu
      service:
        name: apache2
        state: started
      when: ansible_os_family=="Debian"

    - name: i want to install httpd server on redhat
      dnf:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"

    - name: i want to start httpd server on redhat
      service:
        name: httpd
        state: started
      when: ansible_os_family=="RedHat"
