---
- hosts: all
  become: yes
  tasks:
    - name: install apache2 webserver
      apt:
        name: apache2
        state: absent
      when: ansible_os_family=="Debian"

    - name: want to start apache webserver on ubuntu
      service:
        name: apache2
        state: started
      when: ansible_os_family=="Debian"