---
- hosts: all
  become: yes
  tasks:
    - name: install apache2 webserver
      apt:
        name: apache2
        state: present

    - name: want to start apache webserver on ubuntu
      apt:
        name: apache2
        state: started