---
- name: download_tomcat
  get_url:
    url: https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/9.0.55/tomcat-9.0.55.tar.gz
    dest: /home/maha/tomcat-9.0.55.tar.gz
    force_basic_auth: yes

- name: extract files
  file:
    path: /opt/tomcat
    state: directory

- name: extract tar file
  commamd:
    cmd: tar -zvxf apache-tomcat-9.0.55.tar.gz -C /opt/tomcat --strip-components=1 
    creates: /opt/tomcat/LICENSE
     
    